// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVssgr-e7Ru7Yv_bNwmKBgVFcszODtXo',
    appId: '1:397589841703:web:0dacc97c52080949410b02',
    messagingSenderId: '397589841703',
    projectId: 'chatapplication-62e02',
    authDomain: 'chatapplication-62e02.firebaseapp.com',
    storageBucket: 'chatapplication-62e02.appspot.com',
    measurementId: 'G-F2BP33251K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLktiYHTTlQqX03c8t13-FFDiXrZR1Gs',
    appId: '1:397589841703:android:ac0c9264cd5ea6f9410b02',
    messagingSenderId: '397589841703',
    projectId: 'chatapplication-62e02',
    storageBucket: 'chatapplication-62e02.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVssgr-e7Ru7Yv_bNwmKBgVFcszODtXo',
    appId: '1:397589841703:web:1f4d3e5049b0a926410b02',
    messagingSenderId: '397589841703',
    projectId: 'chatapplication-62e02',
    authDomain: 'chatapplication-62e02.firebaseapp.com',
    storageBucket: 'chatapplication-62e02.appspot.com',
    measurementId: 'G-8NEST0GNJF',
  );
}
